-- PreviewService (Script) -> ServerScriptService
-- Set 1 of docs/PREVIEW_PLAN.md. One Studio-only way to see every variant of a
-- generated thing standing in a row, at true scale, labelled. Replaces
-- PetLookPreview, which was written for one kind, marked temporary, and then
-- outlived its own set because a row of eleven silhouettes turned out to be the
-- only way to judge them against each other.
--
-- The whole file returns before it requires anything outside Studio, exactly as
-- EnemyDebug does, so nothing here exists in a live server: no command surface,
-- no folder, no loop.
--
-- Two doors, the same two EnemyDebug takes, because a second convention for the
-- same job is a second thing to remember:
--
--   /preview pets              the row, in catalogue order, in front of you
--   /preview enemies           every type, at true scale, idling
--   /preview enemies spin      the same row turning, for a silhouette check
--   /preview clear             take it away
--
--   game:GetService("ServerScriptService").PreviewCommand:Invoke("enemies")
--
-- A kind is a pure builder plus an enumeration of variants, which is the whole
-- registry entry and the reason this is small: everything else in here is row
-- layout, and row layout does not care what it is laying out.
--
--   name      what you type
--   variants  function(args) -> { { key = <opaque>, label = <string> } }
--   build     function(key) -> Model with a PrimaryPart
--   home      optional, function() -> Folder the models are parented into
--   ready     optional, function(model, entry, index) run after placement
--   spins     optional, whether this kind's row turns unless told otherwise
--
-- `key` is opaque to the service and read only by the kind that emitted it, so
-- a pet's two coordinates and an enemy's one type name are the same interface.
--
-- **Nothing a preview builds is ever tagged**, which is the plan's first
-- invariant and is free here: both builders make geometry and neither has ever
-- called CollectionService. It stops being free at Set 3, where a building is
-- generated by the thing whose entire output is tagged.
--
-- **A row is inert.** Every part is anchored unless a joint holds it, nothing
-- collides, nothing can be touched or queried, and the enemy rigs lose their
-- Humanoid on the way in: a preview enemy that keeps one is a thing with health
-- and a state machine standing in the workspace, and the row is judged on
-- geometry, which a Humanoid contributes none of. That is also the answer to
-- the way this used to be looked at, which was /enemy spawn: twenty live rigs
-- in a ring around you attack immediately, and an enemy you are backing away
-- from is an enemy you are not looking at.
--
-- **Two amendments to the plan, both recorded there.** A kind may name its own
-- `home` folder, because PetAnimator poses workspace.LivePets and only that
-- folder, so a pet row built anywhere else is a row of statues. And the plan's
-- "nothing here drives a joint" is answered for enemies by driving the joints:
-- a still rig hides half of what a type is (a Sentry barely moves at rest and a
-- Swarmer never stops, which reads further down a corridor than any of the
-- geometry does), and a spin over a still rig actively hides it, which is the
-- exact trap the pet row fell into and climbed out of.

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")
local TextChatService = game:GetService("TextChatService")

if not RunService:IsStudio() then
	return
end

local Config = require(ReplicatedStorage:WaitForChild("MazeConfig"))
local EnemyDefinitions = require(ReplicatedStorage:WaitForChild("EnemyDefinitions"))
local ModelGenerator = require(ReplicatedStorage:WaitForChild("ModelGenerator"))
local PetCatalog = require(ReplicatedStorage:WaitForChild("PetCatalog"))
local PetModelGenerator = require(ReplicatedStorage:WaitForChild("PetModelGenerator"))

local EnemyRig = require(script.Parent:WaitForChild("Enemy"):WaitForChild("EnemyRig"))

local FOLDER = "Preview"

-- Laid out by measured width rather than at a fixed pitch, because the kinds are
-- not one size: a Swarmer is a third of a Warden and eleven pets fit in the span
-- twenty enemies need. GAP is the daylight between two neighbours' extents, so
-- the row reads as evenly spaced whatever is standing in it.
local GAP = 2.5
local AHEAD = 16
local HEIGHT = 3

-- The deck, in the same root-local frame the row is laid out in: its top sits
-- DECK_DROP under the models' pivots, it reaches DECK_MARGIN past both ends, and
-- you are set down VIEW_BACK behind the left end of the row.
local DECK_DROP = 1.5
local DECK_THICKNESS = 1
local DECK_MARGIN = 6
local VIEW_BACK = 7

-- Labels stack into an unreadable smear when a row is seen from across the city,
-- which is what made PetLookPreview's on-spawn build intolerable. A MaxDistance
-- means a row left standing is invisible from anywhere you are not deliberately
-- looking at it.
local LABEL_RANGE = 60

-- Both chat doors can be live at once. Keyed on the text rather than on the
-- clock alone, because the double delivery is the same message twice and a
-- second command typed quickly is not. Same rule as EnemyDebug.
local CHAT_ECHO_GRACE = 0.5
local lastChat, lastChatAt = nil, 0

-- ============================================================
-- What a row is made of
-- ============================================================

-- The one Heartbeat connection a row owns, held so that clearing stops it. It
-- was a bare Connect on a row built exactly once, which was fine while the row
-- was built exactly once; rebuilding on a command otherwise leaves one
-- connection per build driving models that have been destroyed.
local loop = nil

-- The placed models, tracked rather than read back off the folder, for two
-- reasons. GetChildren order is not build order, so a spin that pairs a model
-- with someone else's slot spends every frame teleporting past itself. And a
-- kind may park its models in a folder this file does not own, which is then a
-- folder this file must not destroy.
local placed = {}

-- The fake controllers EnemyRig.animate is driven through, one per enemy rig.
-- Its whole surface is this shape: joints and their as-built bases, a clock, a
-- phase, the root it reads velocity off and the torso the head turns against.
-- Nothing here is an EnemyController and nothing pretends to be: an unfrozen
-- table with no target is the idle case, which is the case a row wants.
local animated = {}

local function previewFolder()
	local folder = workspace:FindFirstChild(FOLDER)
	if not folder then
		folder = Instance.new("Folder")
		folder.Name = FOLDER
		folder.Parent = workspace
	end
	return folder
end

-- PetAnimator drives workspace.LivePets and only that folder, so a pet row built
-- into the preview's own folder is a row of statues: a spin overhead reads as
-- motion and hides the fact that no wing is beating. Putting the rigs where the
-- animator already looks costs nothing, because PetService only ever destroys
-- followers it is tracking by player and never sweeps the folder.
--
-- Find-or-create for the usual reason: this can run before PetService has made
-- it. It is deliberately not the general case; see the header.
local function livePets()
	local folder = workspace:FindFirstChild("LivePets")
	if not folder then
		folder = Instance.new("Folder")
		folder.Name = "LivePets"
		folder.Parent = workspace
	end
	return folder
end

-- The plan's third invariant, applied. A part is anchored unless a joint holds
-- it, and the PrimaryPart is anchored regardless, so the rig is one anchored
-- assembly PivotTo carries and the joints pose. Blanket-anchoring everything is
-- exactly the thing that stops a Motor6D from moving anything, which is the
-- shape of the bug that made the first pet row a row of statues.
local function sterilise(model)
	local held = {}
	for _, item in ipairs(model:GetDescendants()) do
		if (item:IsA("Motor6D") or item:IsA("WeldConstraint")) and item.Part1 then
			held[item.Part1] = true
		end
	end
	for _, part in ipairs(model:GetDescendants()) do
		if part:IsA("BasePart") then
			part.Anchored = not held[part] or part == model.PrimaryPart
			part.CanCollide = false
			part.CanTouch = false
			part.CanQuery = false
			part.CastShadow = false
			part.Massless = true
		end
	end
	-- A preview is scenery, and nothing in the row may be discovered by a runtime
	-- service. Neither builder tags anything today; stripping is what keeps that
	-- true of a builder that starts to.
	for _, item in ipairs(model:GetDescendants()) do
		for _, tag in ipairs(item:GetTags()) do
			item:RemoveTag(tag)
		end
	end
	for _, tag in ipairs(model:GetTags()) do
		model:RemoveTag(tag)
	end
end

local function labelFor(model, text)
	local gui = Instance.new("BillboardGui")
	gui.Size = UDim2.fromOffset(200, 26)
	gui.StudsOffsetWorldSpace = Vector3.new(0, model:GetExtentsSize().Y / 2 + 1.4, 0)
	gui.AlwaysOnTop = true
	gui.MaxDistance = LABEL_RANGE
	gui.Parent = model.PrimaryPart

	local name = Instance.new("TextLabel")
	name.Size = UDim2.fromScale(1, 1)
	name.BackgroundTransparency = 1
	name.Font = Enum.Font.GothamBold
	name.TextSize = 16
	name.TextColor3 = Color3.fromRGB(255, 255, 255)
	name.TextStrokeTransparency = 0.4
	name.Text = text
	name.Parent = gui
end

-- ============================================================
-- The registry
-- ============================================================

-- Sorted everywhere below, because pairs over a catalogue is not a stable order
-- and a row that reshuffles between runs is a row you cannot compare against the
-- one you looked at last.
local function sortedKeys(source)
	local keys = {}
	for key in pairs(source) do
		table.insert(keys, key)
	end
	table.sort(keys)
	return keys
end

local kinds = {}

kinds.pets = {
	name = "pets",
	spins = false,
	home = livePets,
	variants = function()
		local entries = {}
		for _, petId in ipairs(sortedKeys(PetCatalog)) do
			local petConfig = PetCatalog[petId]
			for stage = 0, #petConfig.evolutions do
				local evolution = stage > 0 and petConfig.evolutions[stage] or nil
				table.insert(entries, {
					key = { petId = petId, stage = stage },
					label = petConfig.name .. (evolution and (" " .. (evolution.displaySuffix or stage)) or ""),
				})
			end
		end
		return entries
	end,
	build = function(key)
		return PetModelGenerator.build(key.petId, key.stage)
	end,
	-- What PetAnimator reads to know which ability tell to draw, so the Ward
	-- Hound wears its collar here and the Firefly glows, same as in the maze.
	ready = function(model, entry)
		model:SetAttribute("PetId", entry.key.petId)
	end,
}

kinds.enemies = {
	name = "enemies",
	-- On, unlike the pets, and for the opposite half of the same reason. A pet
	-- row is posed by PetAnimator, so a spin there competes with the motion the
	-- row exists to show. Nothing poses an enemy rig on this side, so the idle
	-- below is all the motion there is, and turning is how you see the back of a
	-- silhouette without walking round twenty of them.
	spins = true,
	variants = function()
		local entries = {}
		for _, typeName in ipairs(sortedKeys(EnemyDefinitions.types)) do
			table.insert(entries, { key = typeName, label = EnemyDefinitions.types[typeName].name })
		end
		return entries
	end,
	build = function(typeName)
		return ModelGenerator.build(typeName)
	end,
	ready = function(model, _entry, index)
		-- The rig is built with one, because a live enemy is a Humanoid walking.
		-- Here it is health and a state machine on scenery.
		local humanoid = model:FindFirstChildOfClass("Humanoid")
		if humanoid then
			humanoid:Destroy()
		end

		local anim = ModelGenerator.rigOf(model)
		if not anim then
			return
		end
		table.insert(animated, {
			anim = anim,
			animClock = 0,
			-- Spread deterministically rather than by math.random, so the row
			-- looks the same twice and two neighbours never idle in lockstep.
			phase = (index - 1) * 0.7,
			root = model.PrimaryPart,
			torso = model:FindFirstChild("Torso"),
			frozen = false,
		})
	end,
}

-- ============================================================
-- The row
-- ============================================================

local function clearRow()
	if loop then
		loop:Disconnect()
		loop = nil
	end
	animated = {}

	local cleared = false
	for _, entry in ipairs(placed) do
		if entry.model.Parent then
			entry.model:Destroy()
			cleared = true
		end
	end
	placed = {}

	local folder = workspace:FindFirstChild(FOLDER)
	if folder then
		folder:Destroy()
		cleared = true
	end
	return cleared
end

local function buildRow(kind, root, turning, args)
	clearRow()

	local entries = kind.variants(args)
	if #entries == 0 then
		return "nothing to show"
	end

	-- Built before the row is laid out, because the span is not known until every
	-- model has been measured and the deck has to reach both ends of it.
	local models = {}
	local widths = {}
	local span = 0
	for _, entry in ipairs(entries) do
		local model = kind.build(entry.key)
		sterilise(model)
		local width = model:GetExtentsSize().X
		table.insert(models, model)
		table.insert(widths, width)
		span = span + width + GAP
	end
	span = span - GAP

	local folder = previewFolder()
	local home = kind.home and kind.home() or folder
	local base = root.CFrame

	-- The only collidable thing this file makes, and clearing destroys it, so a
	-- caller who clears while standing on it drops the few studs back to whatever
	-- was underneath.
	local deck = Instance.new("Part")
	deck.Name = "Deck"
	deck.Anchored = true
	deck.CanQuery = false
	deck.Size = Vector3.new(span + DECK_MARGIN * 2, DECK_THICKNESS, VIEW_BACK + DECK_MARGIN)
	deck.CFrame = base * CFrame.new(0, HEIGHT - DECK_DROP - DECK_THICKNESS / 2, -AHEAD + VIEW_BACK / 2)
	deck.Material = Enum.Material.SmoothPlastic
	deck.Color = Color3.fromRGB(38, 40, 46)
	deck.TopSurface = Enum.SurfaceType.Smooth
	deck.Parent = folder

	local cursor = -span / 2
	local parts = 0
	for index, model in ipairs(models) do
		local at = base * CFrame.new(cursor + widths[index] / 2, HEIGHT, -AHEAD)
		model:PivotTo(at)
		labelFor(model, entries[index].label)
		model.Parent = home
		if kind.ready then
			kind.ready(model, entries[index], index)
		end
		parts = parts + #model:GetDescendants()
		table.insert(placed, { model = model, at = at })
		cursor = cursor + widths[index] + GAP
	end

	if turning or #animated > 0 then
		loop = RunService.Heartbeat:Connect(function(dt)
			if turning then
				local turn = math.rad((os.clock() * Config.Pets.SpinDegreesPerSecond) % 360)
				for _, entry in ipairs(placed) do
					entry.model:PivotTo(CFrame.new(entry.at.Position) * CFrame.Angles(0, turn, 0))
				end
			end
			for _, controller in ipairs(animated) do
				EnemyRig.animate(controller, dt)
			end
		end)
	end

	-- The left end, facing the way the caller already was, which is the way the
	-- row faces: walking right reads it in catalogue order. Fifty studs of pets
	-- fits in one view from here; a hundred and twenty of enemies does not, and
	-- walking the row is the intended way to read that one.
	local character = root.Parent
	if character then
		character:PivotTo(base * CFrame.new(-span / 2, HEIGHT - DECK_DROP + 3, -AHEAD + VIEW_BACK))
	end

	return string.format(
		"%s: %d variants, %d instances, %s",
		kind.name,
		#entries,
		parts,
		turning and "turning" or "still"
	)
end

-- ============================================================
-- The dispatcher
-- ============================================================

-- The speaker's own character, falling back to the first player so the command
-- bar door works with no speaker to read a position off.
local function rootFor(speaker)
	local player = speaker or Players:GetPlayers()[1]
	local character = player and player.Character
	return character and character:FindFirstChild("HumanoidRootPart")
end

local function kindList()
	local names = {}
	for name in pairs(kinds) do
		table.insert(names, name)
	end
	table.sort(names)
	return table.concat(names, ", ")
end

local function dispatch(speaker, ...)
	local words = {}
	for _, word in ipairs({ ... }) do
		table.insert(words, string.lower(tostring(word)))
	end

	local head = words[1]
	if head == nil or head == "" or head == "help" then
		return "usage: preview <" .. kindList() .. "|clear> [args] [spin|still]"
	end
	if head == "clear" then
		return clearRow() and "cleared" or "nothing to clear"
	end

	local kind = kinds[head]
	if not kind then
		return "no kind called " .. head .. "; try " .. kindList()
	end
	table.remove(words, 1)

	-- The modifier is the last word and only ever the last word, so a kind that
	-- takes arguments (Set 2's `/preview gear ward_hound`) keeps all of its own.
	local turning = kind.spins
	local tail = words[#words]
	if tail == "spin" or tail == "still" then
		turning = tail == "spin"
		table.remove(words)
	end

	local root = rootFor(speaker)
	if not root then
		return "no character to build in front of"
	end
	return buildRow(kind, root, turning, words)
end

local function run(speaker, ...)
	local result = dispatch(speaker, ...)
	print("[Preview] " .. tostring(result))
	return result
end

-- The chat doors only. The command bar invokes `run` directly, because a script
-- driving this deliberately twice is asking for two builds.
--
-- The two doors do not agree on whether the text they hand back still has the
-- alias on the front of it, and guessing wrong here is invisible: "/preview
-- enemies" arrives as ("enemies") through one and as ("preview", "enemies")
-- through the other, and the second prints the kind list, which reads as a typo
-- rather than as a parse off by one. So the alias is dropped when it is there.
local function argumentsIn(message)
	local words = {}
	for _, word in ipairs(string.split(message, " ")) do
		if word ~= "" then
			table.insert(words, word)
		end
	end
	if words[1] and string.sub(words[1], 1, 1) == "/" then
		table.remove(words, 1)
	end
	return words
end

local function runFromChat(speaker, message)
	local now = os.clock()
	if message == lastChat and now - lastChatAt < CHAT_ECHO_GRACE then
		return
	end
	lastChat, lastChatAt = message, now

	run(speaker, table.unpack(argumentsIn(message)))
end

local bindable = Instance.new("BindableFunction")
bindable.Name = "PreviewCommand"
bindable.OnInvoke = function(...)
	return run(nil, ...)
end
bindable.Parent = script.Parent

-- Which of the two chat doors is live depends entirely on
-- TextChatService.ChatVersion, which default.project.json pins: the modern
-- service reads a leading "/" as a command and does not hand the message to
-- Player.Chatted, the legacy one does the reverse and ignores a TextChatCommand.
-- Unpinned, a row nobody can summon looks exactly like a row that was never
-- written.
local ALIASES = { "/preview", "/look" }

local chatCommand = Instance.new("TextChatCommand")
chatCommand.Name = "PreviewCommand"
chatCommand.PrimaryAlias = ALIASES[1]
chatCommand.SecondaryAlias = ALIASES[2]
chatCommand.Triggered:Connect(function(source, message)
	runFromChat(source and Players:GetPlayerByUserId(source.UserId) or nil, message)
end)
chatCommand.Parent = TextChatService

-- Backfilled as well as connected. In Play Solo the local player can be added
-- before a ServerScriptService script gets to run, and a legacy door hooked only
-- on PlayerAdded then never hears from the one player in the session.
local function hookChatted(player)
	player.Chatted:Connect(function(message)
		local first = string.lower(string.split(message, " ")[1])
		for _, alias in ipairs(ALIASES) do
			if first == alias then
				runFromChat(player, message)
				return
			end
		end
	end)
end

for _, player in ipairs(Players:GetPlayers()) do
	hookChatted(player)
end
Players.PlayerAdded:Connect(hookChatted)

print(string.format("[Preview] ready on %s chat, say /preview %s", TextChatService.ChatVersion.Name, kindList()))
